### PR TITLE
Open files with errors in external editor

### PR DESCRIPTION
**Pull request by manuelbernhardt**
This pull request makes it possible to open compilation errors in an external editor at the correct line.

A URL can be configured via the extensions' "Options..." page (in the Chrome extension list), with the absolute path to the file and the line number . This can be taken advantage of by external editors to directly jump to the file and line.

For IntelliJ IDEA, the RemoteCall plugin (https://github.com/Zolotov/RemoteCall#readme) can be used. In this case the URL to be configured would be `http://localhost:8091?message=$file:$line`

### CODE REVIEW

**Comment by jamesward** [comment]
Thanks!  This will be released shortly.

**Comment by mariussoutier** [comment]
Does this require anything special to work? No matter what I put in, clicking on the link doesn't do anything.

**Comment by manuelbernhardt** [comment]
Did you see the README at
https://github.com/jamesward/play-framework-chrome-tools/blob/master/README.md
?

Basically you need to configure the editor URL in the extension's options,
and point it to an URL that your editor supports. For IDEA there's a plugin
required for opening the file at the correct line (described in the
README), I'm not sure about others (but I know it exists).

Maybe we can find a better place for the set-up instructions.

**Comment by mariussoutier** [comment]
Yes, I configured it for SublimeText (without the config, the URL wouldn't be clickable). But clicking the URL doesn't have any effect. It also doesn't show the configured handler, but only the path to the file.

screen shot 2013-06-14 at 13 44 35

**Comment by manuelbernhardt** [comment]
Could you paste the URL that you configured? The extension triggers a GET
request via AJAX in order to avoid opening a new tab at each click

**Comment by mariussoutier** [comment]
subl://open/?file=$file&line=$line

**Comment by manuelbernhardt** [comment]
Ok, this is because subl:// URLs aren't allowed to be cross-origin. What
I'll do is a fix for this so that this kind of URL gets a plain link.

**Comment by manuelbernhardt** [comment]
I proposed a fix at #2

**Comment by mariussoutier** [comment]
Nevermind, I see, remote call plugin. Maybe something similar can be achieved with Sublime.

**Comment by manuelbernhardt** [comment]
As described on
https://github.com/jamesward/play-framework-chrome-tools/blob/master/README.mdthe
URL for it is
http://localhost:8091?message=$file:$line, i.e. a http URL.

**Pull request merged**
